Closes #49 add hook purl for scripts
pharmaverse/examples pull request #51
Opened 2024-03-07 20:44 UTC by jeffreyad

2024-03-07 20:48 UTC, jeffreyad commented
The scripts are generated when rendered from `knitr::hook_purl`.  The scripts are added to repo once and then would only need to be updated when .qmd files are updated.

If we wanted a more manual process instead, we could add something like this to the tops of the .qmd files.  Then the scripts would only be generated in Posit Cloud or downloaded version.

```
# Run this code to extract an R script
knitr::purl("adam/adppk.qmd", output = "scripts/adppk.R")
```

2024-03-08 08:52 UTC, rossfarrugia commented
oh cool @jeffreyad! happy to defer this one to @can-taslicukur and @bms63 to review and merge if they agree its an easily sustainable solution.

Maybe worth also adding something to the README for this? as we'll need to ensure all new examples include this.

2024-03-08 11:21 UTC, can-taslicukur requested changes
Thank you for this PR @jeffreyad! 🙏 

Although I like this approach because of its simplicity, I would prefer setting these options and hooks project-wide in a single file, instead of repeating them in all documents. I found a way to accomplish this for `knitr::opts_chunk$set(echo = TRUE)` but couldn't for the `knitr::knit_hooks$set(purl = knitr::hook_purl)`. Feel free to also configure it if you can find a way!

Assuming that we have no way to set `knit_hooks` project-wide, I suggest, In README.md, guide developers on adding
```r
```{r setup script, include=FALSE, purl=FALSE}
knitr::knit_hooks$set(purl = knitr::hook_purl)
```
 to new quarto documents and generating `.R` files by rendering the quarto documents every time they make changes to their documents.

2024-03-08 11:21 UTC, can-taslicukur commented on adam/adppk.R
> +metacore <- spec_to_metacore("pk_spec.xlsx") %>%
Running this line in R console fails because the quarto documents use their file directory as a working directory while IDEs (such as Posit Cloud) use the project directory. We can overcome this issue by 

1. Setting [`execute-dir: project`](https://quarto.org/docs/projects/code-execution.html#working-dir) under the `project` entry in `_quarto.yml`
2. Updating the file paths in quarto documents to use a path relative to the project directory (For this case: `adam/pk_spec.xlsx`)
3. Rendering all documents to regenerate .R files with the correct relative path to the file

2024-03-08 11:21 UTC, can-taslicukur commented on adam/adpc.qmd
> +knitr::opts_chunk$set(echo = TRUE)
```suggestion
```

Instead of setting this option across all documents explicitly, we can avoid redundant code by setting

```yml
execute:
  echo: true
```

in _quarto.yml. That way, we do not need to set this every time and we make sure that all documents are echoing.

This comment applies to all quarto documents

2024-03-08 15:06 UTC, bms63 commented
Way cool Jeff!!  Please incorporate @can-taslicukur advice.  

Perhaps we can keep looking for ways to simplify this to reduce overhead...but thank you for making this happen!

2024-03-08 20:54 UTC, jeffreyad commented on adam/adpc.qmd
> +knitr::opts_chunk$set(echo = TRUE)
Thanks @can-taslicukur, sounds good.

2024-04-03 18:53 UTC, bms63 commented
whoa... @jeffreyad sorry I forgot about this one.  Is this good to go?

2024-04-04 20:38 UTC, bms63 approved these changes
I love this!!  Way easier to just have the code and rock it!  @pharmaverse/examples did anyone else want to chime in?

2024-04-05 07:34 UTC, rossfarrugia requested changes
@jeffreyad can you add detail on this to the README contributing section and the new PR template checklist please?

Also i don't see that the advice from @can-taslicukur above was fully implemented but shout if i'm mistaken.

2024-04-25 13:22 UTC, jeffreyad commented
> @jeffreyad did you implement @rossfarrugia requests?

@bms63 I haven't had time to get back to this.  I'll try to take a look.

2024-05-09 18:11 UTC, bms63 approved these changes
Looks good to me!  I'd be interested in trying it out in Posit after it merges.

2024-05-09 18:12 UTC, merged