Closes #14: ADTTE + ADRS with PFS examples
pharmaverse/examples pull request #64
Opened 2024-04-16 18:42 UTC by DavidBlairs

## Pull Request

Howdy. I've had a go at writing up the examples for ADRS and ADTTE with PFS parameters. I think the ADTTE is a good draft (barring any amendment suggestions) but I'm thinking the ADRS article isn't sufficient just yet. 

I was able to get a lot of information about ADTTE with PFS in the vignette provided [here](https://pharmaverse.github.io/admiralonco/articles/adtte.html). However, there was nothing specifically relating to add PFS parameters in the [basic ADRS](https://pharmaverse.github.io/admiralonco/articles/adrs_basic.html) vignette or in the [more detailed version](https://pharmaverse.github.io/admiralonco/articles/adrs.html). I'd appreciate any assistance on this as well as any criticism on the ADRS example. 

@rossfarrugia I added my name in the DESCRIPTION file in another PR, hence why you won't find it here. 

- [X] **Title:** Place `Closes #<insert_issue_number>` at the beginning of your PR title. Use the Edit button in the top-right if you need to update.
- [X] **Linked Issue:** Ensure the related issue is linked in the "Development Section" on the right-hand side.
- [X] **First Contribution:** If this is your first contribution, add yourself to the `DESCRIPTION` file.
- [X] **Impact on Examples:** If your updates impact any examples, review locally for warnings or errors in the impacted example pages.
- [X] **Merge Conflicts:** Developers should address any merge conflicts and merge upon successful review.
- [X] **New Packages:** If new packages were used, ensure they are included in the `DESCRIPTION` file's `Imports` section.
- [X] **Updated Examples:** If you added or updated an example, ensure it runs on the latest CRAN release versions of all packages used.
- [ ] **Testing Instructions:** Provide instructions on how to test the code if necessary.

2024-04-17 10:47 UTC, rossfarrugia commented
thanks @DavidBlairs - will try and take a look over the next week when get chance and sure i could help advise for any gaps.

2024-04-17 15:54 UTC, DavidBlairs commented
Hello @rossfarrugia. Can I just clarify, when the issue says "ADRS and ADTTE with minimal PFS parameters" does that mean:
1. create a minimal ADRS, then use the ADRS to create a minimal ADTTE and add PFS parameters 
2. or does it mean create an ADRS with minimal PFS parameters and create an ADTTE with minimal PFS parameters

2024-04-18 09:45 UTC, rossfarrugia commented
@DavidBlairs probably option 2 is easiest as you can use the pharmaverseadam adrs_onco as input to your ADTTE example as chances are you may need more than the brief example you create here for ADRS and saves you having to save the final dataset in this package to be re-used in your ADTTE example.

2024-04-18 10:30 UTC, DavidBlairs commented
> @DavidBlairs probably option 2 is easiest as you can use the pharmaverseadam adrs_onco as input to your ADTTE example as chances are you may need more than the brief example you create here for ADRS and saves you having to save the final dataset in this repo to be re-used in your ADTTE example.

Debatably, given that the ADRS vignettes don't describe how to add PFS parameters specifically for ADRS, I'd say its easier to have one article thats ADRS -> ADTTE w/ PFS in terms of the documentation available. I'm just not sure if thats acceptable for #14

2024-04-18 10:39 UTC, rossfarrugia commented
@DavidBlairs not sure i understand your point on the ADRS vignette - it shows [here](https://pharmaverse.github.io/admiralonco/articles/adrs.html#pd) how to create disease progression parameter and [here](https://pharmaverse.github.io/admiralonco/articles/adrs.html#death) how to create death parameter, and these 2 then feed into ADTTE to create the PFS parameter.

I haven't had chance to review your PR yet sorry so in case it helps to further clarify here, i was imaging an ADRS example including a disease progression parameter and death parameter, and then an ADTTE example including a PFS parameter using these 2 from an ADRS.

2024-04-24 14:04 UTC, DavidBlairs commented
@rossfarrugia I think this is in a good place to receive critique. I look forward to your feedback

2024-04-25 15:02 UTC, rossfarrugia requested changes
@DavidBlairs thanks for the first draft of these! i made some suggestions from an initial review of mainly the ADRS example. if you could make updates consistently across both then i'd be able to take another look and will spend a bit more time next review on ADTTE. let me know if any of my suggested updates are unclear as to why needed.

2024-04-25 15:06 UTC, rossfarrugia commented on adam/adtte.qmd
> +    censor_conditions = list(lasta_censor, rand_censor),
you need to first include a section on these source objects and how a user could create their own or else this is a bit mystifying, e.g. see https://pharmaverse.github.io/admiralonco/articles/adtte.html#pre-defined-time-to-event-source-objects

2024-05-30 16:13 UTC, DavidBlairs commented
Hello @rossfarrugia. I added these amendments and did a larger rewrite to ensure ADTTE and ADRS were consistent with the ADaM guides already on the examples website. Let me know what you think.

2024-05-31 11:00 UTC, rossfarrugia commented
thanks @DavidBlairs - will try find time over next few weeks to take another look

2024-07-24 10:51 UTC, rossfarrugia requested changes
@DavidBlairs sorry it took me so long to get back around to this. thanks for all the updates! here's some more review comments for consideration.

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adam_spec.xlsx
can delete this copy if you're storing it now in `metadata/` folder

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adrs.qmd
> +```{r read-specs}
add `#| warning: false` under here so that the metacore warnings dont show, liek Jeff did for ADPC

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +```{r, warni}
```suggestion
```{r read-specs}
#| warning: false
```
In ADRS example you included a label like "read-specs" for each step - would be good to have similar in ADTTE just for consistency.

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adrs.qmd
> +tu <- admiral::convert_blanks_to_na(tu)
you dont need to use the `admiral::`, `metacore::` etc convention as the packages are loaded at the top so we have all exported functions available to use, and then its more consistent with the other examples

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adrs.qmd
> +head(adrs_merged, n=10)
maybe the `head()` call is not warranted here as its just a simple merge? might be more effective for this example to only show dataset extracts for the more major steps like deriving new parameters. the admiral vignettes are a bit overkill with these. but i trust your call as to which you leave in and take out

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adrs.qmd
> +```
when i run this block i get the following in console so you might want to update the spec file to better match the dataset you produce:

The following variable(s) were dropped:
  RSACPTFL
Error in `keep()`:
ℹ In index: 1.
Caused by error in `filter()`:
ℹ In argument: `variable %in% names(data)`.
Caused by error in `metatools::check_variables()`:
! The following variables are missing:
SUBJID
SITEID
ASEQ
REGION1
COUNTRY
ETHNIC
AGE
AGEU
AAGE
AAGEU
SEX
RACE
DTHDTC
ITTFL
SAFFL
TRT01P
TRT01A
TRTSDTM
TRTSDT
TRTEDTM
TRTEDT
DCUTDT
RSREFID
RSSPID
RSNAM
RSCAT
RSSCAT
RSSTAT
RSREASND
EPOCH
ADTM
ADY
AVISITN
SRCDOM
SRCVAR
SRCSEQ

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adrs.qmd
> +adrs_xpt <- adrs_lsta %>%
shouldn't the input here be `adrs_checked` once the above comment is resolved?

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +  convert_blanks_to_na()
`convert_blanks_to_na()` should only be needed for datasets originally created with SAS so these pharmaverseadam datasets should be fine without as they were made with admiral

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +This article provides a step-by-step explanation for creating an ADaM `ADTTE` (Time-to-Event) dataset with common oncology endpoint parameters using the `{admiral}`, `{admiralonco}`, `{metacore}`, `{
```suggestion
This article provides a step-by-step explanation for creating an ADaM `ADTTE` (Time-to-Event) dataset with common oncology endpoint parameters using key pharmaverse packages along with tidyverse components. `ADTTE` datasets often involve calculating time-to-event variables for endpoints such as Overall Survival (OS) and Progression-Free Survival (PFS).
```
tried to make a bit more consistent with your ADRS intro above

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +For the purpose of this example, we will use the `adsl` and `adrs_onco` datasets.
```suggestion
For the purpose of this example, we will use the `ADSL` and `ADRS_ONCO` datasets from `{pharmaverseadam}`.
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +We will load our specification file into a `{metacore}` object to trace the dataset variables and attributes. Then, we will read the source data (`adsl` and `adrs_onco`).
```suggestion
We will load our specification file into a `{metacore}` object to trace the dataset variables and attributes. Then, we will read the source data.
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +We define event and censoring sources using the `admiral::event_source` and `admiral::censor_source` functions. This forms the basis for calculating time-to-event endpoints.
```suggestion
We define event and censoring sources using the `admiral::event_source()` and `admiral::censor_source()` functions. This forms the basis for calculating time-to-event endpoints.
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +)
If you use something like the below instead then it has the added value of linking back to your ADRS example where you created DEATH records so makes the 2 examples work nicer together:

```
death_event <- event_source(
  dataset_name = "adrs",
  filter = PARAMCD == "DEATH" & AVALC == "Y" & ANL01FL == "Y",
  date = ADT,
  set_values_to = exprs(
    EVNTDESC = "Death",
    SRCDOM = "ADRS",
    SRCVAR = "ADT"
  )
)
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +
You're missing a last tumor assessment censor that should be used for PFS such as below. The reason this is used in PFS is you can only truly say a patient didn't have a progression up until the point they last had a tumor assessment where diseases progression would have been checked for. Whereas for OS you only check for death and therefore last alive date is fine to use as a censor.

```
lasta_censor <- censor_source(
  dataset_name = "adrs",
  filter = PARAMCD == "LSTA" & ANL01FL == "Y",
  date = ADT,
  set_values_to = exprs(
    EVNTDESC = "Progression Free Alive",
    CNSDTDSC = "Last Tumor Assessment",
    SRCDOM = "ADRS",
    SRCVAR = "ADT"
  )
)
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +    censor_conditions = list(lastalive_censor, rand_censor),
```suggestion
    censor_conditions = list(lasta_censor, rand_censor),
```
See above

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +adtte <- adtte %>%
not needed you could just pipe directly from line 120 and add the comment to the next line

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +adtte <- adtte %>%
As you did for ADRS good idea to use unique names for each dataframe created as easier for people to test out and debug

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +We use `{metatools}` and `{xportr}` to perform checks, apply metadata such as types, lengths, labels, and write the dataset to an XPT file.
make this section consistent to how you have it in ADRS and also clean up specs as it currently gives:

Error in `keep()`:
ℹ In index: 1.
Caused by error in `filter()`:
ℹ In argument: `variable %in% names(data)`.
Caused by error in `check_variables()`:
! The following variables are missing:
AAGE
AAGEU
ITTFL
DCUTDT
PARCAT1
PARCAT2
PARCAT3
AVALU
STARTDTF
ADTF
ADY
SRCSEQ
ANL01FL
The following variables do not belong:
RFSTDTC
RFENDTC
RFXSTDTC
RFXENDTC
RFICDTC
RFPENDTC
DTHDTC
DTHFL
ARMCD
ARM
ACTARMCD
ACTARM
DMDTC
DMDY
TRTSTMF
TRTETMF
TRTDURD
SCRFDT
EOSDT
EOSSTT
FRVDT
DTHDT
DTHDTF
DTHADY
LDDTHELD
DTHCAUS
DTHDOM
DTHCGR1
RACEGR1
AGEGR1
LDDTHGR1
DTH30FL
DTHA30FL
DTHB30FL

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +We derive the sequence number for each record to uniquely identify them using the `admiral::derive_var_obs_number` function.
```suggestion
We derive the sequence number for each record to uniquely identify them using the `admiral::derive_var_obs_number()` function.
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +The analysis value (`AVAL`) can be derived by calling the `admiral::derive_vars_duration` function.
```suggestion
The analysis value (`AVAL`) can be derived by calling the `admiral::derive_vars_duration()` function.
```

2024-07-24 10:51 UTC, rossfarrugia commented on adam/adtte.qmd
> +The `admiral::derive_param_tte` function is used to derive parameters such as OS (Overall Survival) and PFS (Progression-Free Survival).
```suggestion
The `admiral::derive_param_tte()` function is used to derive parameters such as OS (Overall Survival) and PFS (Progression-Free Survival).
```

2024-10-01 09:45 UTC, f-meister commented on metadata/adam_spec.xlsx
renamed file

2024-10-01 09:46 UTC, f-meister commented on adam/adrs.qmd
> +library(tidyr)
I tested it without and don't see a need for this. Removed.

2024-10-02 07:40 UTC, f-meister commented on adam/adtte.qmd
> +We use `{metatools}` and `{xportr}` to perform checks, apply metadata such as types, lengths, labels, and write the dataset to an XPT file.
Cleaned up specs, it doesn't show these anymore.

2024-10-02 10:28 UTC, f-meister commented on adam/adrs.qmd
> +adrs_xpt <- adrs_lsta %>%
you're right. Updated in the latest commit.

2024-10-04 09:04 UTC, rossfarrugia commented on adam/adtte.qmd
> +
@f-meister you updated this correctly for PFS, but for OS you need to leave the old censor object that David had as:

```
lastalive_censor <- censor_source(
  dataset_name = "adsl",
  date = LSTALVDT,
  set_values_to = exprs(
    EVNTDESC = "Last Known Alive",
    CNSDTDSC = "Last Known Alive Date",
    SRCDOM = "ADSL",
    SRCVAR = "LSTALVDT"
  )
)
```

Then use this as the first censor instead of `lasta_censor` for the OS `derive_param_tte()` call below. The reason is a patient can die at any time, not only at a tumor assessment, so we are able to censor at the last point we know they were alive.

2024-10-04 09:14 UTC, rossfarrugia commented
@f-meister one more thing needed is to follow this guidance from the README: https://github.com/pharmaverse/examples#scripts. Once you've done that and made the minor update requested above then i'm going to merge this and if anything else needs fixing i can take it. The CI fail is not related to your examples, so might have to dig into that one if it breaks when in main. I'm wondering if for some reason it's because this one is forked from our repo.

2024-10-07 09:43 UTC, rossfarrugia approved these changes

2024-10-07 09:43 UTC, merged