closes #53 Adding ARD demographics example
pharmaverse/examples pull request #78
Opened 2024-09-13 04:51 UTC by ddsjoberg

## Pull Request

I've added an example using {cards}+{gtsummary} to build a demographics table.
- I did some restructuring of the Demographics page to allow for examples for multiple engines.
- I wasn't able to check the the website build locally. I kept getting WEbAssembly build failures (not something I have played around with in the past).
- There is no issue to link to. Rather @rossfarrugia requested the example be added to the page.

Before you submit your pull request, take a look at the following checklist. Many thanks for your contribution! 

- [x] **Title:** Place `Closes #<insert_issue_number>` at the beginning of your PR title. Use the Edit button in the top-right if you need to update.
- [x] **Linked Issue:** Ensure the related issue is linked in the "Development Section" on the right-hand side.
- [x] **First Contribution:** If this is your first contribution, add yourself to the `DESCRIPTION` file.
- [x] **Impact on Examples:** If your updates impact any examples, review locally for warnings or errors in the impacted example pages.
- [x] **Merge Conflicts:** Developers should address any merge conflicts and merge upon successful review.
- [x] **New Packages:** If new packages were used, ensure they are included in the `DESCRIPTION` file's `Imports` section.
- [x] **Updated Examples:** If you added or updated an example, ensure it runs on the latest CRAN release versions of all packages used.
- [x] **Testing Instructions:** Provide instructions on how to test the code if necessary.

2024-09-16 07:38 UTC, pawelru commented
Hey. Is this still relevant? Looking at the latest commit it looks like it solves the issue in CI (but you said something about local runs).

2024-09-16 09:33 UTC, rossfarrugia commented
thanks @ddsjoberg - will try and review this sometime this week

2024-09-16 11:28 UTC, bms63 commented
> Hey. Is this still relevant? Looking at the latest commit it looks like it solves the issue in CI (but you said something about local runs).

I think we are all good now! :)

2024-09-16 14:48 UTC, ddsjoberg commented
Thanks @rossfarrugia !

@pawelru are there any instructions for rendering the website locally? Is there ayn special setup required for WebAssembly? I made the updates in this PR, but i haven't seen the rendered results yet 😆

2024-09-16 15:14 UTC, pawelru commented
> @pawelru are there any instructions for rendering the website locally? Is there ayn special setup required for WebAssembly? I made the updates in this PR, but i haven't seen the rendered results yet 😆

There is nothing specific about WebAssembly - just make sure that you got all the used packages installed. Here we are using DESCRIPTION file to list them all and `r-lib/actions/setup-r-dependencies` GHA that I assume you are already familiar with. There are instructions [here](https://github.com/pharmaverse/examples/blob/29250e3ed6bec236056b6a6b4896b12e6371e8e5/README.md?plain=1#L69-L74) but you already made it. In CI it has passed [here](https://github.com/pharmaverse/examples/actions/runs/10850644067/job/30112572718). Locally, just run `pak::local_install_deps()` and that's it. Then `quarto render` to render the book. Or `quarto render path/to/art` to render individual article.

2024-09-17 15:33 UTC, ddsjoberg commented
> > @pawelru are there any instructions for rendering the website locally? Is there ayn special setup required for WebAssembly? I made the updates in this PR, but i haven't seen the rendered results yet 😆
> 
> There is nothing specific about WebAssembly - just make sure that you got all the used packages installed. Here we are using DESCRIPTION file to list them all and `r-lib/actions/setup-r-dependencies` GHA that I assume you are already familiar with. There are instructions [here](https://github.com/pharmaverse/examples/blob/29250e3ed6bec236056b6a6b4896b12e6371e8e5/README.md?plain=1#L69-L74) but you already made it. In CI it has passed [here](https://github.com/pharmaverse/examples/actions/runs/10850644067/job/30112572718). Locally, just run `pak::local_install_deps()` and that's it. Then `quarto render` to render the book. Or `quarto render path/to/art` to render individual article.

Thanks @pawelru , I had taken all of those steps. If it helps, here's the error I am seeing locally when rendering the website. It seems to be related to some repo associated with webr. 

@bms63 what error do you see when rendering locally?

```
Warning messages:
1: Can't find MASS in webR binary repository. 
2: Can't find Matrix in webR binary repository. 
3: Package version mismatch for cpp11, ensure the versions below are compatible.
! Installed version: 0.4.7, WebAssembly version: 0.5.0.
ℹ Install a package version matching the WebAssembly version to silence this
  error. 
4: Can't find curl in webR binary repository. 
Execution halted
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 pandoc.pipe.error {command: "Rscript", error_code: 1, output: ""}
Error running filter /Applications/quarto/share/filters/main.lua:
.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
```

2024-09-17 16:35 UTC, ddsjoberg commented
Thank you @pawelru ! I thought i had updated all the packages to the most recent versions, but needed to install cpp11 from source. That resolved that note.

I am still seeing the note about shinylive. I am on the most recent version, however.
![image](https://github.com/user-attachments/assets/d7c7fef6-1839-4334-9f0b-3cbb7d6080d2)

Any other ideas to get this to render? 🙏🏼 

```
Warning messages:
1: Can't find MASS in webR binary repository. 
2: Can't find Matrix in webR binary repository. 
3: Can't find curl in webR binary repository. 
Execution halted
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 pandoc.pipe.error {command: "Rscript", error_code: 1, output: ""}
Error running filter /Applications/quarto/share/filters/main.lua:
.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
```

2024-09-17 16:48 UTC, pawelru commented
I confirm I have the same version. How about this?

```
r$> shinylive::assets_info()
shinylive R package version: 0.2.0
shinylive web assets version: 0.5.0

Local cached shinylive asset dir:
→ /Users/ruckip/Library/Caches/shinylive

Installed assets:
• /Users/ruckip/Library/Caches/shinylive/shinylive-0.5.0
```

Or this:
```
❯ pandoc --version
pandoc 3.2.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/ruckip/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

If not this - I'm run out of ideas :(

I cloned your fork and tried to render it locally from that feature branch. Except from pkgs versions mismatches and missing webr packages - everything works well on my local run.

2024-09-17 18:51 UTC, ddsjoberg commented
welp, thanks for troubeshooting with me @pawelru 

Here's the info below, it looks like it should be all set.

```
> shinylive::assets_info()
shinylive R package version: 0.2.0
shinylive web assets version: 0.5.0

Local cached shinylive asset dir:
→ /Users/sjobergd/Library/Caches/shinylive

Installed assets:
• /Users/sjobergd/Library/Caches/shinylive/shinylive-0.5.0

sjobergd-FV37VC:opt sjobergd$ pandoc --version
pandoc 3.4
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/sjobergd/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

There is another error relating to HTML widgets. I've tried using the CRAN version and the GH version as well. 🤷🏼🤷🏼🤷🏼 😭 

```
Error in `get_github_wasm_assets()`:
! Can't find GitHub release for github::ramnathv/htmlwidgets@master
! Ensure a GitHub release exists for the package repository reference:
  "master".
ℹ Alternatively, install a CRAN version of this package to use the default Wasm
  binary repository.
Caused by error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found:
  <https://api.github.com/repos/ramnathv/htmlwidgets/releases/tags/master>
ℹ Read more at
  <https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name>
Backtrace:
     ▆
  1. └─shinylive:::quarto_ext()
  2.   └─shinylive:::build_app_resources(app_json)
  3.     ├─withr::with_options(...)
  4.     │ └─base::force(code)
  5.     └─shinylive:::download_wasm_packages(appdir, destdir, package_cache = TRUE)
  6.       └─base::lapply(...)
  7.         └─shinylive (local) FUN(X[[i]], ...)
  8.           └─shinylive:::prepare_wasm_metadata(pkg, prev_meta)
  9.             └─shinylive:::get_github_wasm_assets(desc)
 10.               ├─base::tryCatch(...)
 11.               │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 12.               │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 13.               │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 14.               └─gh::gh(...)
 15.                 └─gh:::gh_make_request(req)
 16.                   └─gh:::gh_error(resp, gh_req = x, error_call = error_call)
 17.                     └─cli::cli_abort(...)
 18.                       └─rlang::abort(...)
Warning messages:
1: Can't find MASS in webR binary repository. 
2: Can't find Matrix in webR binary repository. 
3: Can't find curl in webR binary repository. 
Execution halted
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 pandoc.pipe.error {command: "Rscript", error_code: 1, output: ""}
Error running filter /Applications/quarto/share/filters/main.lua:
.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?

stack traceback:
	.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:40: in global 'throw_quarto_error'
	.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:86: in global 'callRShinylive'
	.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:113: in global 'callShinylive'
	.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:437: in function <.../examples/_extensions/quarto-ext/shinylive/shinylive.lua:408>
	[C]: in ?
	[C]: in method 'walk'
	/Applications/quarto/share/filters/main.lua:557: in local 'checked_walk'
	/Applications/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:1334: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/Applications/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
stack traceback:
	/Applications/quarto/share/filters/main.lua:557: in local 'checked_walk'
	/Applications/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
	/Applications/quarto/share/filters/main.lua:1334: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/Applications/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
	/Applications/quarto/share/filters/main.lua:1388: in function </Applications/quarto/share/filters/main.lua:1385>
```

2024-09-18 08:12 UTC, pawelru commented
This I have seen

```
Error in `get_github_wasm_assets()`:
! Can't find GitHub release for github::ramnathv/htmlwidgets@master
! Ensure a GitHub release exists for the package repository reference:
  "master".
ℹ Alternatively, install a CRAN version of this package to use the default Wasm
  binary repository.
Caused by error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found:
  <https://api.github.com/repos/ramnathv/htmlwidgets/releases/tags/master>
ℹ Read more at
  <https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name>
```

My naive understanding of the above is that `webr` (R package) reads your locally installed packages (`packageDescription()` and `Repository` field in particular) and if it's coming from GH then it looks for a tag (?) and webr bundle. What I always do is to over-install that package with the version from CRAN. Up until now that always solved the issue.

2024-09-19 09:37 UTC, rossfarrugia commented
@ddsjoberg hopefully would have some time tomorrow to check this - is it ready? or should i hold off? as i saw more commits coming through

2024-09-19 13:55 UTC, ddsjoberg commented
> @ddsjoberg hopefully would have some time tomorrow to check this - is it ready? or should i hold off? as i saw more commits coming through

@rossfarrugia yep, ready for review, thank you!

2024-09-20 09:29 UTC, rossfarrugia requested changes
@ddsjoberg looks really good to me! only minor comments here. i'd recommend @pawelru also take a look as the original author of this example page.

2024-09-20 09:29 UTC, rossfarrugia commented on tlg/demographic.qmd
> +## Data preprocessing
I think it would benefit from an introductory paragraph above this section to explain that this example guide shows 2 alternative ways to create a table - 1 with respect to ARD and 1 without this

2024-09-20 09:29 UTC, rossfarrugia commented on tlg/demographic.qmd
> +adsl <- pharmaverseadam::adsl |>
should we use `%>%` instead of `|>` here? i know different examples on the site use different conventions here but i feel like within one page it should have consistent usage

2024-09-20 09:29 UTC, rossfarrugia commented on tlg/demographic.qmd
> +In the example below, we will use the [{gtsummary}](https://www.danieldsjoberg.com/gtsummary/) and [{cards}](https://github.com/insightsengineering/cards) packages to create a demographics tables.
I would use the site link for cards rather than the repo link to be consistent with the others

2024-09-20 09:29 UTC, rossfarrugia commented on tlg/demographic.qmd
> +- The {cards} package creates Analysis Results Datasets (ARDs, which are a part of the emerging [CDSIC Analyis Results Standard](https://www.cdisc.org/standards/foundational/analysis-results-standard
```suggestion
- The {cards} package creates Analysis Results Datasets (ARDs, which are a part of the emerging [CDISC Analysis Results Standard](https://www.cdisc.org/standards/foundational/analysis-results-standard)).
```

2024-09-20 09:29 UTC, rossfarrugia commented on tlg/demographic.qmd
> +  missing = "always"
I would remove the "Unknown" all zero rows from the table - and then it closer matches the other example later and we'd never need these all zero rows for an unknown category

2024-09-20 10:57 UTC, pawelru commented on tlg/demographic.qmd
> +adsl <- pharmaverseadam::adsl |>
good point! feel free to convert all to `|>`

2024-09-20 11:00 UTC, pawelru reviewed
This all is good from my side. I basically have similar comments to the ones from @rossfarrugia

2024-09-22 15:37 UTC, ddsjoberg commented on tlg/demographic.qmd
> +## Data preprocessing
Good idea, added!

2024-09-22 15:37 UTC, ddsjoberg commented on tlg/demographic.qmd
> +adsl <- pharmaverseadam::adsl |>
Updated to use the base pipe on the demographics page. like the consistency 👯

2024-09-22 15:37 UTC, ddsjoberg commented on tlg/demographic.qmd
> +In the example below, we will use the [{gtsummary}](https://www.danieldsjoberg.com/gtsummary/) and [{cards}](https://github.com/insightsengineering/cards) packages to create a demographics tables.
ahh, thank you for noting this! updated

2024-09-22 15:38 UTC, ddsjoberg commented on tlg/demographic.qmd
> +- The {cards} package creates Analysis Results Datasets (ARDs, which are a part of the emerging [CDSIC Analyis Results Standard](https://www.cdisc.org/standards/foundational/analysis-results-standard
Thank you for spotting the typo 😬 . Updated!

2024-09-22 15:39 UTC, ddsjoberg commented on tlg/demographic.qmd
> +  missing = "always"
I agree, updated! I had only added them to show similar data to the tern example that has the number non-missing (but gtsummary's default is just a bit easier to show missing instead). 😆

2024-09-22 15:40 UTC, ddsjoberg commented
Thank you @rossfarrugia and @pawelru for the review and assistance with the PR!! I believe all comments have been address 🕺🏼

2024-09-22 15:44 UTC, ddsjoberg commented
I made another small change to the page. I made MALE and FEMALE uppercase in the recode from M/F to match the case of the RACE levels. I can change it back if you'd like.

<img width="877" alt="image" src="https://github.com/user-attachments/assets/7938a24a-dd47-4a15-aa8a-2e36c6679b65">

2024-09-23 10:34 UTC, rossfarrugia commented on tlg/demographic.qmd
> +- The {cards} package creates Analysis Results Datasets (ARDs, which are a part of the [CDSIC Analysis Results Standard](https://www.cdisc.org/standards/foundational/analysis-results-standard)).
```suggestion
- The {cards} package creates Analysis Results Datasets (ARDs, which are a part of the [CDISC Analysis Results Standard](https://www.cdisc.org/standards/foundational/analysis-results-standard)).
```
missed one of the suggested typo corrections

2024-09-23 10:38 UTC, rossfarrugia commented on tlg/demographic.R
> +## ----r preproc----------------------------------------------------------------
@ddsjoberg  this R file should match the updates you made to the qmd. once done i'm happy to approve and merge

2024-09-23 13:54 UTC, ddsjoberg commented on tlg/demographic.R
> +## ----r preproc----------------------------------------------------------------
I can't render the site locally at the moment (some web assembly issues), and it's bit of gymnastics to get this file updated. Apologies for the oversight. Should be updated now.

2024-09-23 14:27 UTC, rossfarrugia approved these changes

2024-09-23 14:27 UTC, merged